travis:
  secure:
    BINSTAR_TOKEN: RONmRcT2luhSptkZvUrUrcxOAHlQyGcws4e/9+XoLR0rZRKYFyqVT3BbdrmMlKayGFS7lnsW7c2aPxYMvHP31YSNwKTShqdfYge65PfKctK/CPkW178ifs/uJo2pO4GQwFokMX2sQC874k2vQBSpHoPOSECG6mPH7VGO1W565vFv7ReZn8VUY/G05KHhgOGgxdgEdfx8vu5JN05ZTfmZoWM9vBk3tKjqObW0qKXebeLOcH5DeYmZwJVgRo8nOBn4x7yxJmtfJXatYi+OtfmMs4Pf/dQmheraW1vLJsxX7JiAhWwDn/VD137uaHeQ+QgzxdtZ5Ltye7BDyv/WgYQxKdZOHvH3KzWSxP5ZSxjzk1dsW+nk5tfrIewVKZvIHkS2JrsBlbzorEjCa4+c/HUB6Nif4EtSQOHF8oRL1t2hTJkirtp0AgSEtkdB32dGfLOLBKHRuPOKZc6sV1H8wgXOpD5vOn9OfYdH9x7qqGD3LplOWnGu1NoJ83Cxxr+KT5ugsJU5LZ6FHrGbPcXNQ57Es+aBz6kfI+FPzgTqPFYieswu2X2YO6pfKw8hmgRPo911bn6REOhMAw7D3mZaNm6HQ4llC2mfA9vQMJIFN+kNSuSo3ms/FS2saDrM+9dmhGdFjz0D0f9H3Zy/qdIuWwv/j1Vb+3IA8FCEY+ngmEqhRzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
min_py_ver: '36'
conda_forge_output_validation: false
